name: Auto Run Main Scripts

on:
  push:                      # langsung jalan kalau ada push
  workflow_dispatch:         # bisa dijalankan manual dari UI
  schedule:
    - cron: "0 */4 * * *"    # otomatis tiap 4 jam

jobs:
  run-main-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run main scripts
        run: |
          python run.py
          python view.py
