name: Auto Run Main & View Scripts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # otomatis tiap 4 jam

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install requests beautifulsoup4 || true

      # Run main scripts
      - name: Run main scripts
        run: |
          python run.py

      # Run view scripts
      - name: Run view scripts
        run: |
          python view.py

      # Upload bokep_pages folder as artifact
      - name: Upload bokep_pages folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bokep-pages
          path: bokep_pages

      # Upload bokep_views folder as artifact
      - name: Upload bokep_views folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bokep-views
          path: bokep_views
